import { expect, test } from '@playwright/test'

test('user session survives refresh, enforces CSRF, and never reports Hook success', async ({ page, context }) => {
  await page.goto('/')
  const create = page.getByRole('button', { name: '创建用户会话', exact: true })
  await expect(create).toBeEnabled()
  await create.click()
  await expect(page.getByRole('heading', { name: '用户会话已建立', exact: true })).toBeVisible()
  const cookies = await context.cookies()
  expect(cookies.find(cookie => cookie.name === 'if-user-dev')?.httpOnly).toBe(true)
  expect(await page.evaluate(() => document.cookie)).not.toContain('if-user-dev')
  const forbidden = await page.evaluate(async () => {
    const response = await fetch('/api/v1/claims/batches', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ codes: ['E2E-TEST'] }) })
    return response.status
  })
  expect(forbidden).toBe(403)
  await page.locator('#invite-codes').fill('E2E-TEST\nE2E-TEST\nSecondCode')
  const result = page.waitForResponse(response => response.url().endsWith('/api/v1/claims/batches'))
  await page.getByRole('button', { name: '提交申请', exact: false }).click()
  expect((await result).status()).toBe(501)
  await expect(page.getByRole('alert')).toContainText('未接入业务 Hook（501）')
  await page.reload()
  await expect(page.getByRole('heading', { name: '用户会话已建立', exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: '退出会话', exact: true }).click()
  await expect(page.getByRole('button', { name: '创建用户会话', exact: true })).toBeVisible()
  expect((await page.request.get('/api/v1/public/session')).status()).toBe(401)
})

test('admin authenticates, reaches protected Hook, and logout revokes the session', async ({ page }) => {
  test.skip(!process.env.INVITEFLOW_TEST_ADMIN_PASSWORD, 'Explicit disposable test admin credentials required')
  await page.goto('/admin')
  await expect(page.locator('#username')).toBeEnabled()
  await page.locator('#username').fill(process.env.INVITEFLOW_TEST_ADMIN_USERNAME || 'admin')
  await page.locator('#password').fill(process.env.INVITEFLOW_TEST_ADMIN_PASSWORD!)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '管理员会话已建立', exact: true })).toBeVisible()
  const result = page.waitForResponse(response => response.url().endsWith('/api/v1/admin/cdk-batches'))
  await page.getByRole('button', { name: '提交批次请求', exact: true }).click()
  expect((await result).status()).toBe(501)
  await expect(page.getByRole('alert')).toContainText('未接入业务 Hook（501）')
  await page.reload()
  await expect(page.getByRole('heading', { name: '管理员会话已建立', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: '退出会话', exact: true }).click()
  await expect(page.locator('#password')).toBeVisible()
  expect((await page.request.get('/api/v1/staff/session')).status()).toBe(401)
})
